version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["gunicorn", "bang.app:app", "--bind", ":8888", "--reload"]
    ports:
      - 8888:8888
